#!/usr/bin/env bash
# Displays DNS records: IP, record type && subdomains

subPrint () {
    printf "The subdomain %s is a " "$subDom"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $5 }'
    printf "\n"
}

subs=("www" "lb-01" "web-01" "web-02")

if [ -z "$2" ];
then
   for subDom in "${subs[@]}";
   do
       subPrint "$1" "$subDom"
   done
else
    subPrint "$1" "$2"
fi
