#!/usr/bin/env bash
#

if [ $# -lt 4 ]
then
    # prompt error msg if less than 4 args
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # if 4 args passed then execute scp command
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$2"@"$3":~/
fi
