#!/usr/bin/env bash
# Installing nginx

apt-get update -y
apt-get install nginx -y
string="rewrite ^/redirect_me$ return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "24i\\\t$string" /etc/nginx/sites-available/default
sudo service nginx restart
