#!/usr/bin/env bash
# Installing nginx

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
string='rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "42i \\\t$string" /etc/nginx/sites-available/default
sudo service nginx restart
