#!/usr/bin/env bash
# Installing nginx

sudo apt-get update -y
sudo apt-get install nginx -y
# | Sending string to index html page
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# | Adding a permanent redirection
string='rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "42i \\\t$string" /etc/nginx/sites-available/default
# | 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
err404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "50i $err404" /etc/nginx/sites-available/default
sudo service nginx restart
