#!/usr/bin/env bash
# Installing && configuring haproxy for redundancy of two servers

# | Updating and installing haproxy
sudo apt-get update -y
sudo apt-get install haproxy -y
# | Variables for servers hostnames
web01="2361-web-01"
web02="2361-web-02"
# | Frontend and Backend configurations lines
frontend="frontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n"
backend="backend backendnodes\n\tbalance roundrobin\n\t$web01 34.139.234.80:80 check\n\t$web02 104.196.35.48:80 check"
# | Insert lines in haproxy.cfg
sudo sed -i ""
# | Restart haproxy service
sudo service haproxy restart
