#!/usr/bin/env bash
# Check if there's arguments by using $#, if not, echo string
# If there's argument then execute command ping with first argument and option

if [ $# -eq 0 ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping $1 -c 5
fi
