#!/usr/bin/env bash
# This bash should print 10 times a string using echo as command
# @_: executes the condition without the need of a variable
# @{1..10}: is the range you want to iterate
# @echo: the command to print to stdout a string

for _ in {1..10}
do
	echo "Best School"
done
