#!/usr/bin/env bash
# this bash will print 10 times a string Variable: char
# Time to print: 1 to 10 String to print: Holberton School
# Command to print output: echo

for _ in {1..10}
do
    echo "Holberton School"
done
