#!/usr/bin/env bash
#will print 1 to 100 and replace acording if:
# n % 3 to Fizz
# n % 5 to Buzz
# n % 15 to FizzBuzz
# else will print the number

n=1
while (( n <= 100 ));
do
    if (( n % 15 == 0));
    then
	echo "FizzBuzz";
    elif (( n % 3 == 0 ));
    then
	echo "Fizz";
    elif (( n % 5 == 0 ));
    then
	echo "Buzz";
    else
	echo "$n";
    fi
    (( n++ ));
done
