#!/usr/bin/env bash
# print Best School to stdout until var val is 9, then print Hi

number=1

while (( number <= 10 ))
do
	echo "Best School";

	if [ $number == 9 ];
	then
		echo "Hi"
	fi
	(( number++ ))
done
