#!/usr/bin/env bash
#will print Holberton School until n is 9 to print Hi
#then continue printin Holberton School until n eq 10

n=0
while (( n <= 10 ))
do
	echo "Holberton School"
	if [ $n = 9 ]
	then
		echo "Hi"
	fi
	(( n++ ));
done
