#!/usr/bin/env bash
# will print Best School until 4th line && 8th line

number=1
while (( number <= 10 ))
do
        if [ $number = 4 ];
        then
                echo "bad luck";
        elif [ $number = 8 ];
        then
                echo "good luck"
        else
                echo "Holberton School"
        fi
        (( number++ ));
done