#!/usr/bin/env bash
#will print HolbertonSchool until 4th line && 8th line

n=1
while (( n <= 10 ))
do
	if [ $n = 4 ];
	then
		echo "bad luck";
	elif [ $n = 8 ];
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	(( n++ ));
done
