#!/usr/bin/env bash
# will print the list of files in the current directory
# and cut the first part before the delim "-"
# cut: it cuts part of a line
# -d is used for delimeters
# -f used to set a field, range of fields or an specific one

ls=$(ls)
for _ in $ls
do
    echo "$_" | cut -d "-" -f 2
done
