#!/usr/bin/env bash
#will test if the file and print a message
#depending on what is testing

file="holbertonschool"
if [ -a "$file" ];
then
    echo "$file file exists"

    if [ -f $file ];
    then
	echo "$file is a regular file"
    fi

    if [ -s "$file" ];
    then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi
else
    echo "$file file does not exist"
fi
